name: ImageryWest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8488
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ImageryWEST
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75327270-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#261C1C'
    - '#011CB3'
    - '#8F8B8B'
    - '#676362'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
