name: ImageryWest
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.02765957
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#261C1C'
    - '#011CB3'
    - '#8F8B8B'
    - '#676362'
  rhythmicContrast: 0
typography_spectrum: 0.3808511
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
