name: ImageryWest
favicon: null
layout_spectrum: 0.3506289725191891
typography_spectrum: 0.723444904666394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6195570577401668
  lightness: 0.7326322838198394
  saturation: 0.31336568971164525
  rhythmicContrast: 0.9830598612315953
purpose: []
